# Generated by Django 6.0.5 on 2026-05-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0004_artistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destaque da Semana'),
        ),
    ]
