# Generated by Django 6.0.5 on 2026-05-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0007_exposicao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exposicao',
            new_name='Exposições',
        ),
    ]
