# Generated by Django 6.0.5 on 2026-05-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0008_rename_exposicao_exposições'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exposições',
            new_name='Exposicao',
        ),
        migrations.AlterModelOptions(
            name='exposicao',
            options={'verbose_name': 'Encontro', 'verbose_name_plural': 'Nossos Encontros'},
        ),
    ]
