# Generated by Django 6.0.5 on 2026-05-24 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0009_rename_exposições_exposicao_alter_exposicao_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileAddress',
            fields=[
                ('address', models.CharField(max_length=255, verbose_name='Rua/Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('postalCode', models.CharField(max_length=20, verbose_name='CEP')),
                ('is_default', models.BooleanField(default=False, verbose_name='Endereço Padrão')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
